pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'shakee_blocki'

include('fabric-1.21.11')
include('fabric-26.1.2')
include('fabric-26.3')

